//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.14
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace RegiFlow.Umbraco.Web.App_Data.Models
{
	// Mixin Content Type with alias "contentSettings"
	/// <summary>Content Settings</summary>
	public partial interface IContentSettings : IPublishedElement
	{
		/// <summary>Enable Scroll-to-top?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		bool EnableScrollToTop { get; }
	}

	/// <summary>Content Settings</summary>
	[PublishedModel("contentSettings")]
	public partial class ContentSettings : PublishedElementModel, IContentSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public new const string ModelTypeAlias = "contentSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ContentSettings(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Enable Scroll-to-top?: If enabled, the scroll-to-top button will be visible.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("enableScrollToTop")]
		public virtual bool EnableScrollToTop => GetEnableScrollToTop(this);

		/// <summary>Static getter for Enable Scroll-to-top?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static bool GetEnableScrollToTop(IContentSettings that) => that.Value<bool>("enableScrollToTop");
	}
}
