//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.14
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace RegiFlow.Umbraco.Web.App_Data.Models
{
	// Mixin Content Type with alias "productSettings"
	/// <summary>Product Settings</summary>
	public partial interface IProductSettings : IPublishedElement
	{
		/// <summary>Billing Period</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		string BillingPeriod { get; }

		/// <summary>Is Free?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		bool IsFree { get; }

		/// <summary>Is Recurring?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		bool IsRecurring { get; }

		/// <summary>Marketing Features</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		global::System.Collections.Generic.IEnumerable<string> MarketingFeatures { get; }

		/// <summary>Price In Pounds</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		decimal PriceInPounds { get; }

		/// <summary>Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		string ProductDescription { get; }

		/// <summary>Product Identifier</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		string ProductIdentifier { get; }

		/// <summary>Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		string ProductName { get; }
	}

	/// <summary>Product Settings</summary>
	[PublishedModel("productSettings")]
	public partial class ProductSettings : PublishedElementModel, IProductSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public new const string ModelTypeAlias = "productSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProductSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ProductSettings(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Billing Period: The frequency of charge.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("billingPeriod")]
		public virtual string BillingPeriod => GetBillingPeriod(this);

		/// <summary>Static getter for Billing Period</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static string GetBillingPeriod(IProductSettings that) => that.Value<string>("billingPeriod");

		///<summary>
		/// Is Free?: If enabled, this product or service is free.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("isFree")]
		public virtual bool IsFree => GetIsFree(this);

		/// <summary>Static getter for Is Free?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static bool GetIsFree(IProductSettings that) => that.Value<bool>("isFree");

		///<summary>
		/// Is Recurring?: If enabled, this is a recurring charge.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("isRecurring")]
		public virtual bool IsRecurring => GetIsRecurring(this);

		/// <summary>Static getter for Is Recurring?</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static bool GetIsRecurring(IProductSettings that) => that.Value<bool>("isRecurring");

		///<summary>
		/// Marketing Features: A list of product features.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("marketingFeatures")]
		public virtual global::System.Collections.Generic.IEnumerable<string> MarketingFeatures => GetMarketingFeatures(this);

		/// <summary>Static getter for Marketing Features</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static global::System.Collections.Generic.IEnumerable<string> GetMarketingFeatures(IProductSettings that) => that.Value<global::System.Collections.Generic.IEnumerable<string>>("marketingFeatures");

		///<summary>
		/// Price In Pounds: The price amount of the product or service.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("priceInPounds")]
		public virtual decimal PriceInPounds => GetPriceInPounds(this);

		/// <summary>Static getter for Price In Pounds</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static decimal GetPriceInPounds(IProductSettings that) => that.Value<decimal>("priceInPounds");

		///<summary>
		/// Description: The description of the product or service.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("productDescription")]
		public virtual string ProductDescription => GetProductDescription(this);

		/// <summary>Static getter for Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static string GetProductDescription(IProductSettings that) => that.Value<string>("productDescription");

		///<summary>
		/// Product Identifier: The UUID of the product.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("productIdentifier")]
		public virtual string ProductIdentifier => GetProductIdentifier(this);

		/// <summary>Static getter for Product Identifier</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static string GetProductIdentifier(IProductSettings that) => that.Value<string>("productIdentifier");

		///<summary>
		/// Name: Name of the product or service.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("productName")]
		public virtual string ProductName => GetProductName(this);

		/// <summary>Static getter for Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static string GetProductName(IProductSettings that) => that.Value<string>("productName");
	}
}
