//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.14
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace RegiFlow.Umbraco.Web.App_Data.Models
{
	/// <summary>Subscription</summary>
	[PublishedModel("subscription")]
	public partial class Subscription : PublishedElementModel, IProductSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public new const string ModelTypeAlias = "subscription";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Subscription, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Subscription(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Billing Period: The frequency of charge.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("billingPeriod")]
		public virtual string BillingPeriod => global::RegiFlow.Umbraco.Web.App_Data.Models.ProductSettings.GetBillingPeriod(this);

		///<summary>
		/// Is Free?: If enabled, this product or service is free.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("isFree")]
		public virtual bool IsFree => global::RegiFlow.Umbraco.Web.App_Data.Models.ProductSettings.GetIsFree(this);

		///<summary>
		/// Is Recurring?: If enabled, this is a recurring charge.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("isRecurring")]
		public virtual bool IsRecurring => global::RegiFlow.Umbraco.Web.App_Data.Models.ProductSettings.GetIsRecurring(this);

		///<summary>
		/// Marketing Features: A list of product features.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("marketingFeatures")]
		public virtual global::System.Collections.Generic.IEnumerable<string> MarketingFeatures => global::RegiFlow.Umbraco.Web.App_Data.Models.ProductSettings.GetMarketingFeatures(this);

		///<summary>
		/// Price In Pounds: The price amount of the product or service.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("priceInPounds")]
		public virtual decimal PriceInPounds => global::RegiFlow.Umbraco.Web.App_Data.Models.ProductSettings.GetPriceInPounds(this);

		///<summary>
		/// Description: The description of the product or service.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("productDescription")]
		public virtual string ProductDescription => global::RegiFlow.Umbraco.Web.App_Data.Models.ProductSettings.GetProductDescription(this);

		///<summary>
		/// Product Identifier: The UUID of the product.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("productIdentifier")]
		public virtual string ProductIdentifier => global::RegiFlow.Umbraco.Web.App_Data.Models.ProductSettings.GetProductIdentifier(this);

		///<summary>
		/// Name: Name of the product or service.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.14")]
		[ImplementPropertyType("productName")]
		public virtual string ProductName => global::RegiFlow.Umbraco.Web.App_Data.Models.ProductSettings.GetProductName(this);
	}
}
